//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
namespace SignetInternet_DataLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CNTSNW10178734\\SQL2008R2;Initial Catalog=LigerUI;Integrated Security=" +
            "True")]
        public string SummaryConnectionString {
            get {
                //return ((string)(this["SummaryConnectionString"]));
                return ConfigurationManager.AppSettings["LigerUIConnectionString"];
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CNTSNW10178734\\SQL2008R2;Initial Catalog=LigerUI;Integrated Security=" +
            "True")]
        public string SignetConnectionString {
            get {
                //return ((string)(this["SignetConnectionString"]));
                return ConfigurationManager.AppSettings["LigerUIConnectionString"];
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CNTSNW10178734\\SQL2008R2;Initial Catalog=LigerUI;Integrated Security=" +
            "True")]
        public string LigerUIConnectionString {
            get {
                //return ((string)(this["LigerUIConnectionString"]));
                return ConfigurationManager.AppSettings["LigerUIConnectionString"];
            }
        }
    }
}
