//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace SignetInternet_BusinessLayer.LockServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IhzbAttenServicebinding", Namespace="http://tempuri.org/")]
    public partial class IhzbAttenServiceservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback hzb_SetPassengerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback hzb_SetDoorOpenOperationCompleted;
        
        private System.Threading.SendOrPostCallback hzb_GetLockerStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback hzb_GetLockerListCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback hzb_GetLockerListDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback hzb_GetOprateResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IhzbAttenServiceservice() {
            this.Url = global::SignetInternet_BusinessLayer.Properties.Settings.Default.SignetInternet_BusinessLayer_LockServices_IhzbAttenServiceservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event hzb_SetPassengerInfoCompletedEventHandler hzb_SetPassengerInfoCompleted;
        
        /// <remarks/>
        public event hzb_SetDoorOpenCompletedEventHandler hzb_SetDoorOpenCompleted;
        
        /// <remarks/>
        public event hzb_GetLockerStatusCompletedEventHandler hzb_GetLockerStatusCompleted;
        
        /// <remarks/>
        public event hzb_GetLockerListCountCompletedEventHandler hzb_GetLockerListCountCompleted;
        
        /// <remarks/>
        public event hzb_GetLockerListDetailCompletedEventHandler hzb_GetLockerListDetailCompleted;
        
        /// <remarks/>
        public event hzb_GetOprateResultCompletedEventHandler hzb_GetOprateResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:hzbAttenService-IhzbAttenService#hzb_SetPassengerInfo", RequestNamespace="urn:hzbAttenService-IhzbAttenService", ResponseNamespace="urn:hzbAttenService-IhzbAttenService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hzb_SetPassengerInfo(int index, string Unit_id, string infovalue) {
            object[] results = this.Invoke("hzb_SetPassengerInfo", new object[] {
                        index,
                        Unit_id,
                        infovalue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hzb_SetPassengerInfoAsync(int index, string Unit_id, string infovalue) {
            this.hzb_SetPassengerInfoAsync(index, Unit_id, infovalue, null);
        }
        
        /// <remarks/>
        public void hzb_SetPassengerInfoAsync(int index, string Unit_id, string infovalue, object userState) {
            if ((this.hzb_SetPassengerInfoOperationCompleted == null)) {
                this.hzb_SetPassengerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhzb_SetPassengerInfoOperationCompleted);
            }
            this.InvokeAsync("hzb_SetPassengerInfo", new object[] {
                        index,
                        Unit_id,
                        infovalue}, this.hzb_SetPassengerInfoOperationCompleted, userState);
        }
        
        private void Onhzb_SetPassengerInfoOperationCompleted(object arg) {
            if ((this.hzb_SetPassengerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hzb_SetPassengerInfoCompleted(this, new hzb_SetPassengerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:hzbAttenService-IhzbAttenService#hzb_SetDoorOpen", RequestNamespace="urn:hzbAttenService-IhzbAttenService", ResponseNamespace="urn:hzbAttenService-IhzbAttenService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hzb_SetDoorOpen(int index, string Unit_id, string doorvalue) {
            object[] results = this.Invoke("hzb_SetDoorOpen", new object[] {
                        index,
                        Unit_id,
                        doorvalue});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hzb_SetDoorOpenAsync(int index, string Unit_id, string doorvalue) {
            this.hzb_SetDoorOpenAsync(index, Unit_id, doorvalue, null);
        }
        
        /// <remarks/>
        public void hzb_SetDoorOpenAsync(int index, string Unit_id, string doorvalue, object userState) {
            if ((this.hzb_SetDoorOpenOperationCompleted == null)) {
                this.hzb_SetDoorOpenOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhzb_SetDoorOpenOperationCompleted);
            }
            this.InvokeAsync("hzb_SetDoorOpen", new object[] {
                        index,
                        Unit_id,
                        doorvalue}, this.hzb_SetDoorOpenOperationCompleted, userState);
        }
        
        private void Onhzb_SetDoorOpenOperationCompleted(object arg) {
            if ((this.hzb_SetDoorOpenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hzb_SetDoorOpenCompleted(this, new hzb_SetDoorOpenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:hzbAttenService-IhzbAttenService#hzb_GetLockerStatus", RequestNamespace="urn:hzbAttenService-IhzbAttenService", ResponseNamespace="urn:hzbAttenService-IhzbAttenService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hzb_GetLockerStatus(int index, string Unit_id, string lockerIdList) {
            object[] results = this.Invoke("hzb_GetLockerStatus", new object[] {
                        index,
                        Unit_id,
                        lockerIdList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hzb_GetLockerStatusAsync(int index, string Unit_id, string lockerIdList) {
            this.hzb_GetLockerStatusAsync(index, Unit_id, lockerIdList, null);
        }
        
        /// <remarks/>
        public void hzb_GetLockerStatusAsync(int index, string Unit_id, string lockerIdList, object userState) {
            if ((this.hzb_GetLockerStatusOperationCompleted == null)) {
                this.hzb_GetLockerStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhzb_GetLockerStatusOperationCompleted);
            }
            this.InvokeAsync("hzb_GetLockerStatus", new object[] {
                        index,
                        Unit_id,
                        lockerIdList}, this.hzb_GetLockerStatusOperationCompleted, userState);
        }
        
        private void Onhzb_GetLockerStatusOperationCompleted(object arg) {
            if ((this.hzb_GetLockerStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hzb_GetLockerStatusCompleted(this, new hzb_GetLockerStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:hzbAttenService-IhzbAttenService#hzb_GetLockerListCount", RequestNamespace="urn:hzbAttenService-IhzbAttenService", ResponseNamespace="urn:hzbAttenService-IhzbAttenService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hzb_GetLockerListCount(int index, string Unit_id, string userinfo) {
            object[] results = this.Invoke("hzb_GetLockerListCount", new object[] {
                        index,
                        Unit_id,
                        userinfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hzb_GetLockerListCountAsync(int index, string Unit_id, string userinfo) {
            this.hzb_GetLockerListCountAsync(index, Unit_id, userinfo, null);
        }
        
        /// <remarks/>
        public void hzb_GetLockerListCountAsync(int index, string Unit_id, string userinfo, object userState) {
            if ((this.hzb_GetLockerListCountOperationCompleted == null)) {
                this.hzb_GetLockerListCountOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhzb_GetLockerListCountOperationCompleted);
            }
            this.InvokeAsync("hzb_GetLockerListCount", new object[] {
                        index,
                        Unit_id,
                        userinfo}, this.hzb_GetLockerListCountOperationCompleted, userState);
        }
        
        private void Onhzb_GetLockerListCountOperationCompleted(object arg) {
            if ((this.hzb_GetLockerListCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hzb_GetLockerListCountCompleted(this, new hzb_GetLockerListCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:hzbAttenService-IhzbAttenService#hzb_GetLockerListDetail", RequestNamespace="urn:hzbAttenService-IhzbAttenService", ResponseNamespace="urn:hzbAttenService-IhzbAttenService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hzb_GetLockerListDetail(int index, string Unit_id, string userinfo, int packageindex) {
            object[] results = this.Invoke("hzb_GetLockerListDetail", new object[] {
                        index,
                        Unit_id,
                        userinfo,
                        packageindex});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hzb_GetLockerListDetailAsync(int index, string Unit_id, string userinfo, int packageindex) {
            this.hzb_GetLockerListDetailAsync(index, Unit_id, userinfo, packageindex, null);
        }
        
        /// <remarks/>
        public void hzb_GetLockerListDetailAsync(int index, string Unit_id, string userinfo, int packageindex, object userState) {
            if ((this.hzb_GetLockerListDetailOperationCompleted == null)) {
                this.hzb_GetLockerListDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhzb_GetLockerListDetailOperationCompleted);
            }
            this.InvokeAsync("hzb_GetLockerListDetail", new object[] {
                        index,
                        Unit_id,
                        userinfo,
                        packageindex}, this.hzb_GetLockerListDetailOperationCompleted, userState);
        }
        
        private void Onhzb_GetLockerListDetailOperationCompleted(object arg) {
            if ((this.hzb_GetLockerListDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hzb_GetLockerListDetailCompleted(this, new hzb_GetLockerListDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:hzbAttenService-IhzbAttenService#hzb_GetOprateResult", RequestNamespace="urn:hzbAttenService-IhzbAttenService", ResponseNamespace="urn:hzbAttenService-IhzbAttenService")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hzb_GetOprateResult(int index, string Unit_id, string schValueInfo) {
            object[] results = this.Invoke("hzb_GetOprateResult", new object[] {
                        index,
                        Unit_id,
                        schValueInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hzb_GetOprateResultAsync(int index, string Unit_id, string schValueInfo) {
            this.hzb_GetOprateResultAsync(index, Unit_id, schValueInfo, null);
        }
        
        /// <remarks/>
        public void hzb_GetOprateResultAsync(int index, string Unit_id, string schValueInfo, object userState) {
            if ((this.hzb_GetOprateResultOperationCompleted == null)) {
                this.hzb_GetOprateResultOperationCompleted = new System.Threading.SendOrPostCallback(this.Onhzb_GetOprateResultOperationCompleted);
            }
            this.InvokeAsync("hzb_GetOprateResult", new object[] {
                        index,
                        Unit_id,
                        schValueInfo}, this.hzb_GetOprateResultOperationCompleted, userState);
        }
        
        private void Onhzb_GetOprateResultOperationCompleted(object arg) {
            if ((this.hzb_GetOprateResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hzb_GetOprateResultCompleted(this, new hzb_GetOprateResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hzb_SetPassengerInfoCompletedEventHandler(object sender, hzb_SetPassengerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hzb_SetPassengerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hzb_SetPassengerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hzb_SetDoorOpenCompletedEventHandler(object sender, hzb_SetDoorOpenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hzb_SetDoorOpenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hzb_SetDoorOpenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hzb_GetLockerStatusCompletedEventHandler(object sender, hzb_GetLockerStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hzb_GetLockerStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hzb_GetLockerStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hzb_GetLockerListCountCompletedEventHandler(object sender, hzb_GetLockerListCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hzb_GetLockerListCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hzb_GetLockerListCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hzb_GetLockerListDetailCompletedEventHandler(object sender, hzb_GetLockerListDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hzb_GetLockerListDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hzb_GetLockerListDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void hzb_GetOprateResultCompletedEventHandler(object sender, hzb_GetOprateResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hzb_GetOprateResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hzb_GetOprateResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591