//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。  
//     技术支持：稻米(www.cnblogs.com/leoxie2011)
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using Liger.Common;
using Liger.Data;

namespace Liger.Model
{

	/// <summary>
	/// 实体类CF_Privilege
	/// </summary>
	[Serializable]
	public class CFPrivilege : Entity 
	{ 
		 public CFPrivilege() 
            : base("CF_Privilege") 
        { 

        }


		#region Model
		private int _PrivilegeID;
		private string _PrivilegeMaster;
		private int _PrivilegeMasterKey;
		private string _PrivilegeAccess;
		private int _PrivilegeAccessKey;
		private string _PrivilegeOperation;
		private int? _CreateUserID;
		private DateTime? _CreateDate;
		private int? _ModifyUserID;
		private DateTime? _ModifyDate;
		private string _RecordStatus;
	 
		/// <summary>
		/// 
		/// </summary>
		public int PrivilegeID
		{
			get{ return _PrivilegeID; }
			set
			{
				this.OnPropertyValueChange(_.PrivilegeID,_PrivilegeID,value);
				this._PrivilegeID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PrivilegeMaster
		{
			get{ return _PrivilegeMaster; }
			set
			{
				this.OnPropertyValueChange(_.PrivilegeMaster,_PrivilegeMaster,value);
				this._PrivilegeMaster = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int PrivilegeMasterKey
		{
			get{ return _PrivilegeMasterKey; }
			set
			{
				this.OnPropertyValueChange(_.PrivilegeMasterKey,_PrivilegeMasterKey,value);
				this._PrivilegeMasterKey = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PrivilegeAccess
		{
			get{ return _PrivilegeAccess; }
			set
			{
				this.OnPropertyValueChange(_.PrivilegeAccess,_PrivilegeAccess,value);
				this._PrivilegeAccess = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int PrivilegeAccessKey
		{
			get{ return _PrivilegeAccessKey; }
			set
			{
				this.OnPropertyValueChange(_.PrivilegeAccessKey,_PrivilegeAccessKey,value);
				this._PrivilegeAccessKey = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PrivilegeOperation
		{
			get{ return _PrivilegeOperation; }
			set
			{
				this.OnPropertyValueChange(_.PrivilegeOperation,_PrivilegeOperation,value);
				this._PrivilegeOperation = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CreateUserID
		{
			get{ return _CreateUserID; }
			set
			{
				this.OnPropertyValueChange(_.CreateUserID,_CreateUserID,value);
				this._CreateUserID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ModifyUserID
		{
			get{ return _ModifyUserID; }
			set
			{
				this.OnPropertyValueChange(_.ModifyUserID,_ModifyUserID,value);
				this._ModifyUserID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ModifyDate
		{
			get{ return _ModifyDate; }
			set
			{
				this.OnPropertyValueChange(_.ModifyDate,_ModifyDate,value);
				this._ModifyDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RecordStatus
		{
			get{ return _RecordStatus; }
			set
			{
				this.OnPropertyValueChange(_.RecordStatus,_RecordStatus,value);
				this._RecordStatus = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.PrivilegeID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.PrivilegeID			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.PrivilegeID,
				_.PrivilegeMaster,
				_.PrivilegeMasterKey,
				_.PrivilegeAccess,
				_.PrivilegeAccessKey,
				_.PrivilegeOperation,
				_.CreateUserID,
				_.CreateDate,
				_.ModifyUserID,
				_.ModifyDate,
				_.RecordStatus
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				_PrivilegeID,
				_PrivilegeMaster,
				_PrivilegeMasterKey,
				_PrivilegeAccess,
				_PrivilegeAccessKey,
				_PrivilegeOperation,
				_CreateUserID,
				_CreateDate,
				_ModifyUserID,
				_ModifyDate,
				_RecordStatus
			};
		} 
		/// <summary>
		/// 设置字段值
		/// </summary>
		public override void SetValue(string fieldName, object value)
        {
            switch (fieldName)
            { 
				case "PrivilegeID":
                    this._PrivilegeID = DataHelper.ConvertValue<int>(value);
                    break; 
				case "PrivilegeMaster":
                    this._PrivilegeMaster = DataHelper.ConvertValue<string>(value);
                    break; 
				case "PrivilegeMasterKey":
                    this._PrivilegeMasterKey = DataHelper.ConvertValue<int>(value);
                    break; 
				case "PrivilegeAccess":
                    this._PrivilegeAccess = DataHelper.ConvertValue<string>(value);
                    break; 
				case "PrivilegeAccessKey":
                    this._PrivilegeAccessKey = DataHelper.ConvertValue<int>(value);
                    break; 
				case "PrivilegeOperation":
                    this._PrivilegeOperation = DataHelper.ConvertValue<string>(value);
                    break; 
				case "CreateUserID":
                    this._CreateUserID = DataHelper.ConvertValue<int?>(value);
                    break; 
				case "CreateDate":
                    this._CreateDate = DataHelper.ConvertValue<DateTime?>(value);
                    break; 
				case "ModifyUserID":
                    this._ModifyUserID = DataHelper.ConvertValue<int?>(value);
                    break; 
				case "ModifyDate":
                    this._ModifyDate = DataHelper.ConvertValue<DateTime?>(value);
                    break; 
				case "RecordStatus":
                    this._RecordStatus = DataHelper.ConvertValue<string>(value);
                    break; 
            }
        }
		/// <summary>
		/// 获取字段值
		/// </summary>
        public override object GetValue(string fieldName)
        {
            switch (fieldName)
            { 
				case "PrivilegeID":
                    return this._PrivilegeID; 
				case "PrivilegeMaster":
                    return this._PrivilegeMaster; 
				case "PrivilegeMasterKey":
                    return this._PrivilegeMasterKey; 
				case "PrivilegeAccess":
                    return this._PrivilegeAccess; 
				case "PrivilegeAccessKey":
                    return this._PrivilegeAccessKey; 
				case "PrivilegeOperation":
                    return this._PrivilegeOperation; 
				case "CreateUserID":
                    return this._CreateUserID; 
				case "CreateDate":
                    return this._CreateDate; 
				case "ModifyUserID":
                    return this._ModifyUserID; 
				case "ModifyDate":
                    return this._ModifyDate; 
				case "RecordStatus":
                    return this._RecordStatus; 
				default :
                    return null;
            } 
        }



		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CF_Privilege");
 
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivilegeID = new Field("PrivilegeID","CF_Privilege","PrivilegeID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivilegeMaster = new Field("PrivilegeMaster","CF_Privilege","PrivilegeMaster");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivilegeMasterKey = new Field("PrivilegeMasterKey","CF_Privilege","PrivilegeMasterKey");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivilegeAccess = new Field("PrivilegeAccess","CF_Privilege","PrivilegeAccess");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivilegeAccessKey = new Field("PrivilegeAccessKey","CF_Privilege","PrivilegeAccessKey");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivilegeOperation = new Field("PrivilegeOperation","CF_Privilege","PrivilegeOperation");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID","CF_Privilege","CreateUserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","CF_Privilege","CreateDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifyUserID = new Field("ModifyUserID","CF_Privilege","ModifyUserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifyDate = new Field("ModifyDate","CF_Privilege","ModifyDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RecordStatus = new Field("RecordStatus","CF_Privilege","RecordStatus");
		}
		#endregion

 
	}
}


