//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。  
//     技术支持：稻米(www.cnblogs.com/leoxie2011)
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using Liger.Common;
using Liger.Data;

namespace Liger.Model
{

	/// <summary>
	/// 实体类CF_User
	/// </summary>
	[Serializable]
	public class CFUser : Entity 
	{ 
		 public CFUser() 
            : base("CF_User") 
        { 

        }


		#region Model
		private int _UserID;
		private string _LoginName;
		private string _LoginPassword;
		private string _DeptID;
        private string _SupplierID;
        private string _EmployeeID;
		private string _RealName;
		private string _Title;
		private string _Sex;
		private string _Phone;
		private string _Fax;
		private string _Email;
		private string _IDCard;
		private string _NickName;
		private string _Address;
		private DateTime? _LastLoginTime;
		private int? _CreateUserID;
		private DateTime? _CreateDate;
		private int? _ModifyUserID;
		private DateTime? _ModifyDate;
		private string _RecordStatus;
	 
		/// <summary>
		/// 
		/// </summary>
		public int UserID
		{
			get{ return _UserID; }
			set
			{
				this.OnPropertyValueChange(_.UserID,_UserID,value);
				this._UserID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LoginName
		{
			get{ return _LoginName; }
			set
			{
				this.OnPropertyValueChange(_.LoginName,_LoginName,value);
				this._LoginName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LoginPassword
		{
			get{ return _LoginPassword; }
			set
			{
				this.OnPropertyValueChange(_.LoginPassword,_LoginPassword,value);
				this._LoginPassword = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
        public string DeptID
		{
			get{ return _DeptID; }
			set
			{
				this.OnPropertyValueChange(_.DeptID,_DeptID,value);
				this._DeptID = value;
			}
		}
		/// <summary>
		/// 该用户属于 供应商
		/// </summary>
        public string SupplierID
		{
			get{ return _SupplierID; }
			set
			{
				this.OnPropertyValueChange(_.SupplierID,_SupplierID,value);
				this._SupplierID = value;
			}
		}
		/// <summary>
		/// 该用户属于 雇员
		/// </summary>
        public string EmployeeID
		{
			get{ return _EmployeeID; }
			set
			{
				this.OnPropertyValueChange(_.EmployeeID,_EmployeeID,value);
				this._EmployeeID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RealName
		{
			get{ return _RealName; }
			set
			{
				this.OnPropertyValueChange(_.RealName,_RealName,value);
				this._RealName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Sex
		{
			get{ return _Sex; }
			set
			{
				this.OnPropertyValueChange(_.Sex,_Sex,value);
				this._Sex = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Phone
		{
			get{ return _Phone; }
			set
			{
				this.OnPropertyValueChange(_.Phone,_Phone,value);
				this._Phone = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Fax
		{
			get{ return _Fax; }
			set
			{
				this.OnPropertyValueChange(_.Fax,_Fax,value);
				this._Fax = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string IDCard
		{
            get { return _IDCard; }
			set
			{
                this.OnPropertyValueChange(_.IDCard, _IDCard, value);
                this._IDCard = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string NickName
		{
			get{ return _NickName; }
			set
			{
				this.OnPropertyValueChange(_.NickName,_NickName,value);
				this._NickName = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address = value;
			}
		}
		/// <summary>
		/// 最后登录时间
		/// </summary>
		public DateTime? LastLoginTime
		{
			get{ return _LastLoginTime; }
			set
			{
				this.OnPropertyValueChange(_.LastLoginTime,_LastLoginTime,value);
				this._LastLoginTime = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? CreateUserID
		{
			get{ return _CreateUserID; }
			set
			{
				this.OnPropertyValueChange(_.CreateUserID,_CreateUserID,value);
				this._CreateUserID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? CreateDate
		{
			get{ return _CreateDate; }
			set
			{
				this.OnPropertyValueChange(_.CreateDate,_CreateDate,value);
				this._CreateDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? ModifyUserID
		{
			get{ return _ModifyUserID; }
			set
			{
				this.OnPropertyValueChange(_.ModifyUserID,_ModifyUserID,value);
				this._ModifyUserID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? ModifyDate
		{
			get{ return _ModifyDate; }
			set
			{
				this.OnPropertyValueChange(_.ModifyDate,_ModifyDate,value);
				this._ModifyDate = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RecordStatus
		{
			get{ return _RecordStatus; }
			set
			{
				this.OnPropertyValueChange(_.RecordStatus,_RecordStatus,value);
				this._RecordStatus = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的标识列
		/// </summary>
		public override Field GetIdentityField()
		{
			return _.UserID;
		}
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.UserID			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.UserID,
				_.LoginName,
				_.LoginPassword,
				_.DeptID,
				_.SupplierID,
				_.EmployeeID,
				_.RealName,
				_.Title,
				_.Sex,
				_.Phone,
				_.Fax,
				_.Email,
				_.IDCard,
				_.NickName,
				_.Address,
				_.LastLoginTime,
				_.CreateUserID,
				_.CreateDate,
				_.ModifyUserID,
				_.ModifyDate,
				_.RecordStatus
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				_UserID,
				_LoginName,
				_LoginPassword,
				_DeptID,
				_SupplierID,
				_EmployeeID,
				_RealName,
				_Title,
				_Sex,
				_Phone,
				_Fax,
				_Email,
				_IDCard,
				_NickName,
				_Address,
				_LastLoginTime,
				_CreateUserID,
				_CreateDate,
				_ModifyUserID,
				_ModifyDate,
				_RecordStatus
			};
		} 
		/// <summary>
		/// 设置字段值
		/// </summary>
		public override void SetValue(string fieldName, object value)
        {
            switch (fieldName)
            { 
				case "UserID":
                    this._UserID = DataHelper.ConvertValue<int>(value);
                    break; 
				case "LoginName":
                    this._LoginName = DataHelper.ConvertValue<string>(value);
                    break; 
				case "LoginPassword":
                    this._LoginPassword = DataHelper.ConvertValue<string>(value);
                    break; 
				case "DeptID":
                    this._DeptID = DataHelper.ConvertValue<string>(value);
                    break; 
				case "SupplierID":
                    this._SupplierID = DataHelper.ConvertValue<string>(value);
                    break; 
				case "EmployeeID":
                    this._EmployeeID = DataHelper.ConvertValue<string>(value);
                    break; 
				case "RealName":
                    this._RealName = DataHelper.ConvertValue<string>(value);
                    break; 
				case "Title":
                    this._Title = DataHelper.ConvertValue<string>(value);
                    break; 
				case "Sex":
                    this._Sex = DataHelper.ConvertValue<string>(value);
                    break; 
				case "Phone":
                    this._Phone = DataHelper.ConvertValue<string>(value);
                    break; 
				case "Fax":
                    this._Fax = DataHelper.ConvertValue<string>(value);
                    break; 
				case "Email":
                    this._Email = DataHelper.ConvertValue<string>(value);
                    break; 
				case "IDCard":
                    this._IDCard = DataHelper.ConvertValue<string>(value);
                    break; 
				case "NickName":
                    this._NickName = DataHelper.ConvertValue<string>(value);
                    break; 
				case "Address":
                    this._Address = DataHelper.ConvertValue<string>(value);
                    break; 
				case "LastLoginTime":
                    this._LastLoginTime = DataHelper.ConvertValue<DateTime?>(value);
                    break; 
				case "CreateUserID":
                    this._CreateUserID = DataHelper.ConvertValue<int?>(value);
                    break; 
				case "CreateDate":
                    this._CreateDate = DataHelper.ConvertValue<DateTime?>(value);
                    break; 
				case "ModifyUserID":
                    this._ModifyUserID = DataHelper.ConvertValue<int?>(value);
                    break; 
				case "ModifyDate":
                    this._ModifyDate = DataHelper.ConvertValue<DateTime?>(value);
                    break; 
				case "RecordStatus":
                    this._RecordStatus = DataHelper.ConvertValue<string>(value);
                    break; 
            }
        }
		/// <summary>
		/// 获取字段值
		/// </summary>
        public override object GetValue(string fieldName)
        {
            switch (fieldName)
            { 
				case "UserID":
                    return this._UserID; 
				case "LoginName":
                    return this._LoginName; 
				case "LoginPassword":
                    return this._LoginPassword; 
				case "DeptID":
                    return this._DeptID; 
				case "SupplierID":
                    return this._SupplierID; 
				case "EmployeeID":
                    return this._EmployeeID; 
				case "RealName":
                    return this._RealName; 
				case "Title":
                    return this._Title; 
				case "Sex":
                    return this._Sex; 
				case "Phone":
                    return this._Phone; 
				case "Fax":
                    return this._Fax; 
				case "Email":
                    return this._Email; 
				case "IDCard":
                    return this._IDCard; 
				case "NickName":
                    return this._NickName; 
				case "Address":
                    return this._Address; 
				case "LastLoginTime":
                    return this._LastLoginTime; 
				case "CreateUserID":
                    return this._CreateUserID; 
				case "CreateDate":
                    return this._CreateDate; 
				case "ModifyUserID":
                    return this._ModifyUserID; 
				case "ModifyDate":
                    return this._ModifyDate; 
				case "RecordStatus":
                    return this._RecordStatus; 
				default :
                    return null;
            } 
        }



		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CF_User");
 
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field UserID = new Field("UserID","CF_User","UserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginName = new Field("LoginName","CF_User","LoginName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LoginPassword = new Field("LoginPassword","CF_User","LoginPassword");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptID = new Field("DeptID","CF_User","DeptID");
			/// <summary>
			/// 该用户属于 供应商
			/// </summary>
			public readonly static Field SupplierID = new Field("SupplierID","CF_User","SupplierID");
			/// <summary>
			/// 该用户属于 雇员
			/// </summary>
			public readonly static Field EmployeeID = new Field("EmployeeID","CF_User","EmployeeID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RealName = new Field("RealName","CF_User","RealName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Title = new Field("Title","CF_User","Title");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex","CF_User","Sex");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone","CF_User","Phone");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Fax = new Field("Fax","CF_User","Fax");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email","CF_User","Email");
			/// <summary>
			/// 
			/// </summary>
            public readonly static Field IDCard = new Field("IDCard", "CF_User", "IDCard");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field NickName = new Field("NickName","CF_User","NickName");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address","CF_User","Address");
			/// <summary>
			/// 最后登录时间
			/// </summary>
			public readonly static Field LastLoginTime = new Field("LastLoginTime","CF_User","LastLoginTime");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateUserID = new Field("CreateUserID","CF_User","CreateUserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CreateDate = new Field("CreateDate","CF_User","CreateDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifyUserID = new Field("ModifyUserID","CF_User","ModifyUserID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ModifyDate = new Field("ModifyDate","CF_User","ModifyDate");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RecordStatus = new Field("RecordStatus","CF_User","RecordStatus");
		}
		#endregion

 
	}
}


