//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。  
//     技术支持：稻米(www.cnblogs.com/leoxie2011)
//     对此文件的更改可能会导致不正确的行为
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.Common;
using Liger.Common;
using Liger.Data;

namespace Liger.Model
{

	/// <summary>
	/// 实体类EmployeeCustomers
	/// </summary>
	[Serializable]
	public class EmployeeCustomers : Entity 
	{ 
		 public EmployeeCustomers() 
            : base("EmployeeCustomers") 
        { 

        }


		#region Model
		private string _CustomerId;
		private int? _EmployeeId;
	 
		/// <summary>
		/// 
		/// </summary>
		public string CustomerId
		{
			get{ return _CustomerId; }
			set
			{
				this.OnPropertyValueChange(_.CustomerId,_CustomerId,value);
				this._CustomerId = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public int? EmployeeId
		{
			get{ return _EmployeeId; }
			set
			{
				this.OnPropertyValueChange(_.EmployeeId,_EmployeeId,value);
				this._EmployeeId = value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.CustomerId			};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CustomerId,
				_.EmployeeId
			};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				_CustomerId,
				_EmployeeId
			};
		} 
		/// <summary>
		/// 设置字段值
		/// </summary>
		public override void SetValue(string fieldName, object value)
        {
            switch (fieldName)
            { 
				case "CustomerId":
                    this._CustomerId = DataHelper.ConvertValue<string>(value);
                    break; 
				case "EmployeeId":
                    this._EmployeeId = DataHelper.ConvertValue<int?>(value);
                    break; 
            }
        }
		/// <summary>
		/// 获取字段值
		/// </summary>
        public override object GetValue(string fieldName)
        {
            switch (fieldName)
            { 
				case "CustomerId":
                    return this._CustomerId; 
				case "EmployeeId":
                    return this._EmployeeId; 
				default :
                    return null;
            } 
        }



		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","EmployeeCustomers");
 
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomerId = new Field("CustomerId","EmployeeCustomers","CustomerId");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field EmployeeId = new Field("EmployeeId","EmployeeCustomers","EmployeeId");
		}
		#endregion

 
	}
}


