//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36440
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.36440 版自动生成。
// 
#pragma warning disable 1591

namespace SignetInternet_BusinessLayer.SMS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CommonServicesSoap", Namespace="http://tempuri.org/")]
    public partial class CommonServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authentication authenticationValueField;
        
        private System.Threading.SendOrPostCallback GetAreasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSignetAreasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendIdentifyCodeMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBinHaiIdentifyCodeMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBinHaiMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateIdentifyCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CommonServices() {
            this.Url = global::SignetInternet_BusinessLayer.Properties.Settings.Default.SignetInternet_BusinessLayer_SMS_CommonServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authentication AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAreasCompletedEventHandler GetAreasCompleted;
        
        /// <remarks/>
        public event GetSignetAreasCompletedEventHandler GetSignetAreasCompleted;
        
        /// <remarks/>
        public event SendIdentifyCodeMsgCompletedEventHandler SendIdentifyCodeMsgCompleted;
        
        /// <remarks/>
        public event SendBinHaiIdentifyCodeMsgCompletedEventHandler SendBinHaiIdentifyCodeMsgCompleted;
        
        /// <remarks/>
        public event SendMsgCompletedEventHandler SendMsgCompleted;
        
        /// <remarks/>
        public event SendBinHaiMsgCompletedEventHandler SendBinHaiMsgCompleted;
        
        /// <remarks/>
        public event ValidateIdentifyCodeCompletedEventHandler ValidateIdentifyCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAreas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAreas(string status) {
            object[] results = this.Invoke("GetAreas", new object[] {
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAreasAsync(string status) {
            this.GetAreasAsync(status, null);
        }
        
        /// <remarks/>
        public void GetAreasAsync(string status, object userState) {
            if ((this.GetAreasOperationCompleted == null)) {
                this.GetAreasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAreasOperationCompleted);
            }
            this.InvokeAsync("GetAreas", new object[] {
                        status}, this.GetAreasOperationCompleted, userState);
        }
        
        private void OnGetAreasOperationCompleted(object arg) {
            if ((this.GetAreasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAreasCompleted(this, new GetAreasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSignetAreas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSignetAreas(string status) {
            object[] results = this.Invoke("GetSignetAreas", new object[] {
                        status});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSignetAreasAsync(string status) {
            this.GetSignetAreasAsync(status, null);
        }
        
        /// <remarks/>
        public void GetSignetAreasAsync(string status, object userState) {
            if ((this.GetSignetAreasOperationCompleted == null)) {
                this.GetSignetAreasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSignetAreasOperationCompleted);
            }
            this.InvokeAsync("GetSignetAreas", new object[] {
                        status}, this.GetSignetAreasOperationCompleted, userState);
        }
        
        private void OnGetSignetAreasOperationCompleted(object arg) {
            if ((this.GetSignetAreasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSignetAreasCompleted(this, new GetSignetAreasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendIdentifyCodeMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendIdentifyCodeMsg(string phone) {
            object[] results = this.Invoke("SendIdentifyCodeMsg", new object[] {
                        phone});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendIdentifyCodeMsgAsync(string phone) {
            this.SendIdentifyCodeMsgAsync(phone, null);
        }
        
        /// <remarks/>
        public void SendIdentifyCodeMsgAsync(string phone, object userState) {
            if ((this.SendIdentifyCodeMsgOperationCompleted == null)) {
                this.SendIdentifyCodeMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendIdentifyCodeMsgOperationCompleted);
            }
            this.InvokeAsync("SendIdentifyCodeMsg", new object[] {
                        phone}, this.SendIdentifyCodeMsgOperationCompleted, userState);
        }
        
        private void OnSendIdentifyCodeMsgOperationCompleted(object arg) {
            if ((this.SendIdentifyCodeMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendIdentifyCodeMsgCompleted(this, new SendIdentifyCodeMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBinHaiIdentifyCodeMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBinHaiIdentifyCodeMsg(string phone) {
            object[] results = this.Invoke("SendBinHaiIdentifyCodeMsg", new object[] {
                        phone});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBinHaiIdentifyCodeMsgAsync(string phone) {
            this.SendBinHaiIdentifyCodeMsgAsync(phone, null);
        }
        
        /// <remarks/>
        public void SendBinHaiIdentifyCodeMsgAsync(string phone, object userState) {
            if ((this.SendBinHaiIdentifyCodeMsgOperationCompleted == null)) {
                this.SendBinHaiIdentifyCodeMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBinHaiIdentifyCodeMsgOperationCompleted);
            }
            this.InvokeAsync("SendBinHaiIdentifyCodeMsg", new object[] {
                        phone}, this.SendBinHaiIdentifyCodeMsgOperationCompleted, userState);
        }
        
        private void OnSendBinHaiIdentifyCodeMsgOperationCompleted(object arg) {
            if ((this.SendBinHaiIdentifyCodeMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBinHaiIdentifyCodeMsgCompleted(this, new SendBinHaiIdentifyCodeMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMsg(string phone, string msg) {
            object[] results = this.Invoke("SendMsg", new object[] {
                        phone,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendMsgAsync(string phone, string msg) {
            this.SendMsgAsync(phone, msg, null);
        }
        
        /// <remarks/>
        public void SendMsgAsync(string phone, string msg, object userState) {
            if ((this.SendMsgOperationCompleted == null)) {
                this.SendMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMsgOperationCompleted);
            }
            this.InvokeAsync("SendMsg", new object[] {
                        phone,
                        msg}, this.SendMsgOperationCompleted, userState);
        }
        
        private void OnSendMsgOperationCompleted(object arg) {
            if ((this.SendMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMsgCompleted(this, new SendMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBinHaiMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBinHaiMsg(string phone, string msg) {
            object[] results = this.Invoke("SendBinHaiMsg", new object[] {
                        phone,
                        msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBinHaiMsgAsync(string phone, string msg) {
            this.SendBinHaiMsgAsync(phone, msg, null);
        }
        
        /// <remarks/>
        public void SendBinHaiMsgAsync(string phone, string msg, object userState) {
            if ((this.SendBinHaiMsgOperationCompleted == null)) {
                this.SendBinHaiMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBinHaiMsgOperationCompleted);
            }
            this.InvokeAsync("SendBinHaiMsg", new object[] {
                        phone,
                        msg}, this.SendBinHaiMsgOperationCompleted, userState);
        }
        
        private void OnSendBinHaiMsgOperationCompleted(object arg) {
            if ((this.SendBinHaiMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBinHaiMsgCompleted(this, new SendBinHaiMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateIdentifyCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateIdentifyCode(string phone, string number) {
            object[] results = this.Invoke("ValidateIdentifyCode", new object[] {
                        phone,
                        number});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateIdentifyCodeAsync(string phone, string number) {
            this.ValidateIdentifyCodeAsync(phone, number, null);
        }
        
        /// <remarks/>
        public void ValidateIdentifyCodeAsync(string phone, string number, object userState) {
            if ((this.ValidateIdentifyCodeOperationCompleted == null)) {
                this.ValidateIdentifyCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateIdentifyCodeOperationCompleted);
            }
            this.InvokeAsync("ValidateIdentifyCode", new object[] {
                        phone,
                        number}, this.ValidateIdentifyCodeOperationCompleted, userState);
        }
        
        private void OnValidateIdentifyCodeOperationCompleted(object arg) {
            if ((this.ValidateIdentifyCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateIdentifyCodeCompleted(this, new ValidateIdentifyCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36430")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader {
        
        private string userIDField;
        
        private string passWordField;
        
        private string timeStampField;
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public string TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetAreasCompletedEventHandler(object sender, GetAreasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAreasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAreasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetSignetAreasCompletedEventHandler(object sender, GetSignetAreasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSignetAreasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSignetAreasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void SendIdentifyCodeMsgCompletedEventHandler(object sender, SendIdentifyCodeMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendIdentifyCodeMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendIdentifyCodeMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void SendBinHaiIdentifyCodeMsgCompletedEventHandler(object sender, SendBinHaiIdentifyCodeMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBinHaiIdentifyCodeMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBinHaiIdentifyCodeMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void SendMsgCompletedEventHandler(object sender, SendMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void SendBinHaiMsgCompletedEventHandler(object sender, SendBinHaiMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBinHaiMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBinHaiMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ValidateIdentifyCodeCompletedEventHandler(object sender, ValidateIdentifyCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateIdentifyCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateIdentifyCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591